### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by karolinku** [tylerdotrar/mkdocs-coverpage#2]
Could you clarify the license for this project? I noticed that https://github.com/up42/up42-py is MIT, but I don't see the same here. I'm asking because I like the template and would like to use it in my project.

**Comment by tylerdotrar** [comment]
Added licensing! Use it however you like boss.

**Comment by KarthikAbiram** [comment]
First, thank you @tylerdotrar for this mkdocs coverpage template :)

My 2 cents - On the licensing, I see that the license currently chosen is GPL-3. In case if you would like to people to use however they want, I would recommend choosing MIT/BSD/Apache, which is more permissive and free to use for both open source and commercial projects. As [mkdocs-material license is MIT](https://squidfunk.github.io/mkdocs-material/license/), I would recommend the same to keep things simple for users.
